### ISSUE TITLE
Maybe a small mistake in README.md 

### ISSUE THREAD

**Issue by ChenxiTU** [1zb/pytorch-image-comp-rnn#3]
In 
## Encode and Decode
You mention that 
### Decode
`
python decoder.py --model checkpoint/encoder_epoch_00000005.pth --input /path/to/your/example.npz --cuda --output /path/to/output/folder
`
Maybe here should be checkpoint/decoder_epoch_00000005.pth?

**Comment by Jillian2017** [comment]
Hi @ChenxiTU,
when running the encopy.py, i come across a error :TypeError:super( ) takes at least 1 argument(0 given)
in binarizer = network.Binarizer( ), the super() function is in modules/sign.py. Have you ever met such bug before?

**Comment by ChenxiTU** [comment]
@Jillian2017 
Sorry, until now I just tried comments given by author and have not met any bug.

**Comment by Jillian2017** [comment]
I got，thanks.

**Comment by alexgo1** [comment]
I think it's because you tried running it with Python 2. Try Python 3,  or use the "super(ClassName, self)" syntax instead

**Comment by Jillian2017** [comment]
hi @alexgo1, I have tried python 3, and I meet the error below:
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    loss.backward() #loss.backward(create_graph=True)
  File "/home/sunqp/py3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/sunqp/py3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: function SignBackward returned an incorrect number of gradients (expected 2, got 1).
This error appears both in python2.7 and python 3.

**Comment by alexgo1** [comment]
@Jillian2017 , have you seen the fix suggested in #4 ?

**Comment by Jillian2017** [comment]
@alexgo1, yeah, I find it, thanks a lot.
